### ISSUE TITLE
Action Costs supported?

### ISSUE THREAD

**Issue by nirlipo** [planimation/backend#19]
I was trying to planimate this problem:
- [editor.domains link to files](http://editor.planning.domains/#read_session=fcg84iOqIK)

but I get an incorrect visualization:

![image](https://user-images.githubusercontent.com/861782/90456454-5c3cd780-e13c-11ea-9ffa-7b5dc8f671bc.png)

 
Is this error a result of using PDDL action costs syntax? If that's the case, we could just ignore action costs effects and functions in the problem and domain files, and think later about how to visualize action costs.

If I run the same domain removing action costs from the problem, I get the correct visualization:

![image](https://user-images.githubusercontent.com/861782/90456431-534c0600-e13c-11ea-993c-c920fa29af96.png)

Best,

**Comment by nirlipo** [comment]
# Documentation on how to use costs in PDDL 

In terms of information about the use of costs in PDDL see below: 
- An Introduction to the Planning Domain Definition Language - [Free e-copy in UoM Library](https://ebookcentral.proquest.com/lib/unimelb/detail.action?docID=5746725) 
    - See logistics example, page 24. Action costs are introduced in page 33. This is the subset that just allow to express action costs, where the objective function is to minimize the special numeric fluent (total-cost) 
        - PDDL example: http://editor.planning.domains/pddl-book/linehaul_with_costs 
    - See chapter 4 for generic numeric planning, where predicates can take numeric values (functions) instead of boolean. https://ebookcentral.proquest.com/lib/unimelb/reader.action?docID=5746725&ppg=103 
- Initially, I'd aim to parse and visualize only action costs. Then we can build up towards numeric fluents.   

# Find visualitzation toolkits / examples relevant to visualization of costs (temporal) / resources (time-series) AI visualization 

I haven't found anything interesting to be honest. So far, this is the existing simple visualization of a temporal plan:  
![image](https://user-images.githubusercontent.com/861782/78224260-f72d7000-7513-11ea-9433-6618c2dc733c.png)

You can access this by going to editor.planning.domains -> plugins -> install timeline viewer. http://editor.planning.domains/#read_session=qZxJB4b2Ht 

This simply takes the plan file actions, and place them below using the initial time(first number) and their duration number within square brackets [].   

There's some literature of tools visualizing temporal planning but I can't find anything that applies just to costs/numeric planning.

# Types of semantics visualization that can get attached to costs
      
Below I discuss few possible visualizations of costs and visual semantics that can be attached to them.

## No semantic  
- You can visualize the costs as a counter, and when an action is executed, you show its added cost. 
- Make the animation go slower as a function of the cost of the action   

## Distances 

Foreach predicate/function defined in the initial state, we can associate it witha drawing e.g. A line, an image, etc. and allow to:   
- make the cost change the width of the drawing 
- make the cost change the length of the drawing 
- make the cost change the color of the drawing (going from 0 as cold color, and big numbers a red, sort of like a heatmap colour scheme) 

PDDLexamples:
- http://editor.planning.domains/pddl-book/linehaul_with_costs 
- Transport domain: 
    - Domain: https://bitbucket.org/planning-researchers/classical-domains/src/db6cabb001850e7a49419eece889e3976af4e18d/classical/transport-opt14-strips/domain.pddl?at=master 
    - Problem: https://bitbucket.org/planning-researchers/classical-domains/src/db6cabb001850e7a49419eece889e3976af4e18d/classical/transport-opt14-strips/p01.pddl?at=master   

## Resources  

Draw a reservoir, and allow to define: max, min, and units. Then we can assign the cost or function/predicate to a specific reservoir. We have to see where in the UI we can add this 
![image](https://user-images.githubusercontent.com/861782/78224550-791d9900-7514-11ea-8656-50518ab4aab1.png)

PDDLExample: 
- Transport domain (capacity): 
    - Domain: https://bitbucket.org/planning-researchers/classical-domains/src/db6cabb001850e7a49419eece889e3976af4e18d/classical/transport-opt14-strips/domain.pddl?at=master 
    - Problem: https://bitbucket.org/planning-researchers/classical-domains/src/db6cabb001850e7a49419eece889e3976af4e18d/classical/transport-opt14-strips/p01.pddl?at=master 
- No-Mistery (fuel): 
    - Domain: https://bitbucket.org/planning-researchers/classical-domains/src/db6cabb001850e7a49419eece889e3976af4e18d/classical/nomystery-opt11-strips/domain.pddl?at=master 
    - Problem: https://bitbucket.org/planning-researchers/classical-domains/src/db6cabb001850e7a49419eece889e3976af4e18d/classical/nomystery-opt11-strips/p01.pddl?at=master  

Note that in these two examples, capacity and fuel are expressed through predicates instead of functions, as it assumes no use of numeric variables, just action costs.This leads to the encoding of boolean predicates representing numbers, where the initial state expresses basic arithmetic such as sum, greater, smaller, etc. Think how can you associate these predicates into a visualization like the above. It may need a special function, similar to what we have for associating a set of predicates into a grid: https://planimation.github.io/documentation/ap_guide/#25-functions

## Stock and Flows

[Loopy ](https://ncase.me/loopy/) is a nice visualization tool for systems thinking. We can take it as an inspiration to visualize flows and stocks, which are similar to reservoirs.

Explore some avilable [demos ](https://ncase.me/loopy/v1.1/?data=[[[1,181,181,0,%22automation%22,0],[2,486,175,0,%22profits%22,0],[3,369,482,0,%22job%2520loss%22,4],[4,567,513,0,%22frustration%22,4],[5,752,432,0,%22political%2520unrest%22,4],[6,655,283,0,%22tax%2520revenue%22,3]],[[1,3,-88,1,0],[1,2,-150,1,0],[2,1,-137,1,0],[3,4,-27,1,0],[4,5,-32,1,0],[2,6,12,1,0]],[[331,197,%22vicious%2520cycle%250Aof%2520automation%250Aleads%2520to%2520short-%250Aterm%2520job%2520loss%252C%250Athen%2520frustration%252C%250Athen%2520political%250Aunrest%22],[733,143,%22CHALLENGE%253A%250Athink%2520up%2520and%2520model%2520your%250Aown%2520solutions%2520to%2520this%2520problem!%250A(hint%253A%2520what%2520tax-funded%2520programs%250Acould%2520mitigate%2520job%2520loss%2520due%2520to%250Aautomation%253F)%22],[489,383,%22%253F%253F%253F%2520what%2520goes%2520here%2520%253F%253F%253F%22]],6]) provided by loopy and how it visualizes concepts

![image](https://user-images.githubusercontent.com/861782/78229315-8e49f600-751b-11ea-9261-c381025d0b17.png)

This type of semantics can be very helpful for some numeric fluents problems and lead to temporal planning visualizations.

**Comment by JamieYuu** [comment]
Currently, on the branch feature/19-action-cost, the program can handle the PDDL files mentioned above. However, it only hardcoding the keywords "traverse-cost" and "total-cost" (for example, https://github.com/planimation/backend/blob/feature/19-action-cost/server/app/vfg/parser/Plan_generator.py#L126). The parser functions in the backend needs to be updated to handling complex PDDL syntax, maybe using some third-party libraries is a better option. Due to this reason, this branch is not merged into the develop branch yet.
We found some potential libraries:
https://pypi.org/project/pddlpy/
https://github.com/garydoranjr/pyddl

I also updated the predicate list generator function: https://github.com/planimation/backend/blob/125d6b020d8efc0bacc55f831781827921ed9b16/server/app/vfg/parser/Domain_parser.py#L34.

**Comment by chillray** [comment]
> Currently, on the branch feature/19-action-cost, the program can handle the PDDL files mentioned above. However, it only hardcoding the keywords "traverse-cost" and "total-cost" (for example, https://github.com/planimation/backend/blob/feature/19-action-cost/server/app/vfg/parser/Plan_generator.py#L126). The parser functions in the backend needs to be updated to handling complex PDDL syntax, maybe using some third-party libraries is a better option. Due to this reason, this branch is not merged into the develop branch yet. We found some potential libraries: https://pypi.org/project/pddlpy/ https://github.com/garydoranjr/pyddl
> 
> I also updated the predicate list generator function:
> 
> https://github.com/planimation/backend/blob/125d6b020d8efc0bacc55f831781827921ed9b16/server/app/vfg/parser/Domain_parser.py#L34
> .

Regarding the flexibility issue, our solution on the branch feature/19-action-cost-v2 allows users to specify the action cost keyword in the animation profile themselves. The backend will handle action costs based on the cost_keyword specified by the user.

However, we don't think this is the perfect solution, as it only supports one action cost_keyword. What if there are two separated action costs for Truck1 and Truck2?
