### ISSUE TITLE
Unable to reach network

### ISSUE THREAD

**Issue by zhenxied** [planimation/backend#39]
Hi,

The planimation plugin returned "Unable to reach network." as shown below, but I am sure there was nothing wrong with my network.

![Capture](https://user-images.githubusercontent.com/44262714/92712633-50d87700-f39d-11ea-8ba9-b17460435c2c.PNG)

Then I realised that the problem was the comment line in objects field in my problem3.pddl file.

![Capture1](https://user-images.githubusercontent.com/44262714/92712717-677ece00-f39d-11ea-809d-d8e77b95ca01.PNG)

That is, if I have this comment line here, the planimation cannot generate animation and will return an Error message "Unable to reach network.". After I deleted this line, it works fine.

**Comment by JamieYuu** [comment]
Hi @zhenxied , can you send the PDDL files (domain, problem, and animation) that occur the error to us? My email address is jiazhengy@student.unimelb.edu.au
Thank you.
